#!/bin/bash
cd "$(dirname "$0")/../../../"
if [ ! -d "venv" ]; then
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
else
    source venv/bin/activate
fi
python app.py &
sleep 2
open http://127.0.0.1:5555
wait
